defaults:
<<<<<<< HEAD
  - user: TODO_your_username
=======
  - user: minah
>>>>>>> origin/main
  - model: PlanT

exp_folder_name: PlanT2_train
hydra:
  run:
    dir: outputs/${exp_folder_name}/${expname}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - expname
        kv_sep: '='
        item_sep: '_'

lrDecay_epoch: 29

# Seed is set by environment variable
# seed: 1234
debug: False
visualize: False
overfit: 0
resume: True
resume_path: ""
use_caching: True
custom_sampler: False
<<<<<<< HEAD
gpus: 2
=======
gpus: 1
>>>>>>> origin/main

expname: DEBUG
wandb_name: training_PlanT_${hydra:job.override_dirname}
save_dir: ${hydra:run.dir}

# NOTE: This is unused currently and replaced by the DS environment variable to allow SLURM local paths
<<<<<<< HEAD
data_dir: /home/simon/PlanT_2_cleanup/PlanT_2_2025_07_24/data

=======
# data_dir: /home/simon/PlanT_2_cleanup/PlanT_2_2025_07_24/data
data_dir: /workspace/data/PlanT_2_dataset/data
>>>>>>> origin/main
