name: plant2
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025a=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beartype==0.20.0
      - carla==0.9.15
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - dictor==0.1.12
      - diskcache==5.6.3
      - docker-pycreds==0.4.0
      - ephem==4.2
      - filelock==3.18.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - h5py==3.14.0
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lightning==2.5.0.post0
      - lightning-utilities==0.14.1
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.2.0
      - networkx==3.4.2
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.1.0
      - platformdirs==4.3.6
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - py-trees==0.8.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.4
      - pyparsing==3.2.1
      - pytorch-lightning==2.5.0.post0
      - pyyaml==6.0.2
      - rdp==0.8
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scipy==1.15.2
      - sentry-sdk==2.23.1
      - setproctitle==1.3.5
      - shapely==2.0.7
      - simple-watchdog-timer==0.1.1
      - smmap==5.0.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - timm==1.0.19
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchmetrics==1.6.3
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - transforms3d==0.4.2
      - triton==3.2.0
      - typing-extensions==4.12.2
      - ujson==5.10.0
      - urllib3==2.3.0
      - wandb==0.19.8
      - werkzeug==3.1.3
      - yarl==1.18.3
prefix: /home/simon/miniconda3/envs/plant_2
